service: quotes

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 1024
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: application.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'